# lebron_per_game.csv data_cleaning

### Step 1: Load Libraries

Remember:
- Pandas is Data Cleaning
- Matplotlib is Data visuals
- Numpy is Math Operations/Calculator

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import psycopg2
from pandasql import sqldf
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
pd.options.plotting.backend = 'plotly'
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
import voila
import warnings
warnings.filterwarnings('ignore')

### Step 2: Explore the Data

In [2]:
#importing the csv data into python
#store it as a dataframe df
# Reading the path piece by piece:
#.. goes up one folder, from notebooks/ to lebron-data-story/
#/data goes into the data folder
#/raw goes into the raw folder
#/lebron_per_game.csv is the file

df = pd.read_csv('../data/raw/lebron_per_game.csv')
df

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2003-04,19,CLE,NBA,SG,79,79,39.5,7.9,18.9,...,1.3,4.2,5.5,5.9,1.6,0.7,3.5,1.9,20.9,MVP-9ROY-1
1,2004-05,20,CLE,NBA,SF,80,80,42.4,9.9,21.1,...,1.4,6,7.4,7.2,2.2,0.7,3.3,1.8,27.2,MVP-6ASNBA2
2,2005-06,21,CLE,NBA,SF,79,79,42.5,11.1,23.1,...,0.9,6.1,7,6.6,1.6,0.8,3.3,2.3,31.4,MVP-2ASNBA1
3,2006-07,22,CLE,NBA,SF,78,78,40.9,9.9,20.8,...,1.1,5.7,6.7,6,1.6,0.7,3.2,2.2,27.3,MVP-5ASNBA2
4,2007-08,23,CLE,NBA,SF,75,74,40.4,10.6,21.9,...,1.8,6.1,7.9,7.2,1.8,1.1,3.4,2.2,30,MVP-4ASNBA1
5,2008-09,24,CLE,NBA,SF,81,81,37.7,9.7,19.9,...,1.3,6.3,7.6,7.2,1.7,1.1,3,1.7,28.4,MVP-1DPOY-2ASNBA1DEF1
6,2009-10,25,CLE,NBA,SF,76,76,39,10.1,20.1,...,0.9,6.4,7.3,8.6,1.6,1,3.4,1.6,29.7,MVP-1DPOY-4ASNBA1DEF1
7,2010-11,26,MIA,NBA,SF,79,79,38.8,9.6,18.8,...,1,6.5,7.5,7,1.6,0.6,3.6,2.1,26.7,MVP-3DPOY-9ASNBA1DEF1
8,2011-12,27,MIA,NBA,SF,62,62,37.5,10,18.9,...,1.5,6.4,7.9,6.2,1.9,0.8,3.4,1.5,27.1,MVP-1DPOY-4ASNBA1DEF1
9,2012-13,28,MIA,NBA,PF,76,76,37.9,10.1,17.8,...,1.3,6.8,8,7.3,1.7,0.9,3,1.4,26.8,MVP-1DPOY-2ASNBA1DEF1
10,2013-14,29,MIA,NBA,PF,77,77,37.7,10,17.6,...,1.1,5.9,6.9,6.3,1.6,0.3,3.5,1.6,27.1,MVP-2DPOY-6ASNBA1DEF2
11,2014-15,30,CLE,NBA,SF,69,69,36.1,9,18.5,...,0.7,5.3,6,7.4,1.6,0.7,3.9,2,25.3,MVP-3DPOY-13ASNBA1
12,2015-16,31,CLE,NBA,SF,76,76,35.6,9.7,18.6,...,1.5,6,7.4,6.8,1.4,0.6,3.3,1.9,25.3,MVP-3DPOY-11ASNBA1
13,2016-17,32,CLE,NBA,SF,74,74,37.8,9.9,18.2,...,1.3,7.3,8.6,8.7,1.2,0.6,4.1,1.8,26.4,MVP-4DPOY-5ASNBA1
14,2017-18,33,CLE,NBA,PF,82,82,36.9,10.5,19.3,...,1.2,7.5,8.6,9.1,1.4,0.9,4.2,1.7,27.5,MVP-2ASNBA1
15,2018-19,34,LAL,NBA,SF,55,55,35.2,10.1,19.9,...,1,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,MVP-11ASNBA3
16,2019-20,35,LAL,NBA,PG,67,67,34.6,9.6,19.4,...,1,6.9,7.8,10.2,1.2,0.5,3.9,1.8,25.3,MVP-2ASNBA1
17,2020-21,36,LAL,NBA,PG,45,45,33.4,9.4,18.3,...,0.6,7,7.7,7.8,1.1,0.6,3.7,1.6,25,MVP-13ASNBA2
18,2021-22,37,LAL,NBA,C,56,56,37.2,11.4,21.8,...,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,MVP-10ASNBA3
19,2022-23,38,LAL,NBA,PF,55,54,35.5,11.1,22.2,...,1.2,7.1,8.3,6.8,0.9,0.6,3.2,1.6,28.9,ASNBA3
20,2023-24,39,LAL,NBA,PF,71,71,35.3,9.6,17.9,...,0.9,6.4,7.3,8.3,1.3,0.5,3.5,1.1,25.7,CPOY-10ASNBA3
21,2024-25,40,LAL,NBA,SF,70,70,34.9,9.3,18.1,...,1,6.8,7.8,8.2,1,0.6,3.7,1.4,24.4,MVP-6CPOY-7ASNBA2
22,2025-26,41,LAL,NBA,SF,60,60,33.2,7.9,15.3,...,0.7,5.4,6.1,7.2,1.2,0.6,3,1.4,20.9,AS
23,NaN,NaN,NaN,NaN,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
24,23 Yrs,23 Yrs,23 Yrs,23 Yrs,NaN,1622,1620,37.6,9.8,19.4,...,1.1,6.3,7.5,7.4,1.5,0.7,3.5,1.8,26.8,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),NaN,849,848,39,9.9,20,...,1.2,6.1,7.3,7.3,1.6,0.8,3.5,1.9,27.2,NaN
27,LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),NaN,479,478,34.9,9.8,19,...,1,6.7,7.7,7.9,1.2,0.6,3.5,1.6,25.9,NaN
28,MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),NaN,294,294,38,9.9,18.2,...,1.2,6.4,7.6,6.7,1.7,0.7,3.4,1.7,26.9,NaN

In [3]:
#always make a copy of the df to protect the og
dfcopy = df.copy()
dfcopy

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2003-04,19,CLE,NBA,SG,79,79,39.5,7.9,18.9,...,1.3,4.2,5.5,5.9,1.6,0.7,3.5,1.9,20.9,MVP-9ROY-1
1,2004-05,20,CLE,NBA,SF,80,80,42.4,9.9,21.1,...,1.4,6,7.4,7.2,2.2,0.7,3.3,1.8,27.2,MVP-6ASNBA2
2,2005-06,21,CLE,NBA,SF,79,79,42.5,11.1,23.1,...,0.9,6.1,7,6.6,1.6,0.8,3.3,2.3,31.4,MVP-2ASNBA1
3,2006-07,22,CLE,NBA,SF,78,78,40.9,9.9,20.8,...,1.1,5.7,6.7,6,1.6,0.7,3.2,2.2,27.3,MVP-5ASNBA2
4,2007-08,23,CLE,NBA,SF,75,74,40.4,10.6,21.9,...,1.8,6.1,7.9,7.2,1.8,1.1,3.4,2.2,30,MVP-4ASNBA1
5,2008-09,24,CLE,NBA,SF,81,81,37.7,9.7,19.9,...,1.3,6.3,7.6,7.2,1.7,1.1,3,1.7,28.4,MVP-1DPOY-2ASNBA1DEF1
6,2009-10,25,CLE,NBA,SF,76,76,39,10.1,20.1,...,0.9,6.4,7.3,8.6,1.6,1,3.4,1.6,29.7,MVP-1DPOY-4ASNBA1DEF1
7,2010-11,26,MIA,NBA,SF,79,79,38.8,9.6,18.8,...,1,6.5,7.5,7,1.6,0.6,3.6,2.1,26.7,MVP-3DPOY-9ASNBA1DEF1
8,2011-12,27,MIA,NBA,SF,62,62,37.5,10,18.9,...,1.5,6.4,7.9,6.2,1.9,0.8,3.4,1.5,27.1,MVP-1DPOY-4ASNBA1DEF1
9,2012-13,28,MIA,NBA,PF,76,76,37.9,10.1,17.8,...,1.3,6.8,8,7.3,1.7,0.9,3,1.4,26.8,MVP-1DPOY-2ASNBA1DEF1
10,2013-14,29,MIA,NBA,PF,77,77,37.7,10,17.6,...,1.1,5.9,6.9,6.3,1.6,0.3,3.5,1.6,27.1,MVP-2DPOY-6ASNBA1DEF2
11,2014-15,30,CLE,NBA,SF,69,69,36.1,9,18.5,...,0.7,5.3,6,7.4,1.6,0.7,3.9,2,25.3,MVP-3DPOY-13ASNBA1
12,2015-16,31,CLE,NBA,SF,76,76,35.6,9.7,18.6,...,1.5,6,7.4,6.8,1.4,0.6,3.3,1.9,25.3,MVP-3DPOY-11ASNBA1
13,2016-17,32,CLE,NBA,SF,74,74,37.8,9.9,18.2,...,1.3,7.3,8.6,8.7,1.2,0.6,4.1,1.8,26.4,MVP-4DPOY-5ASNBA1
14,2017-18,33,CLE,NBA,PF,82,82,36.9,10.5,19.3,...,1.2,7.5,8.6,9.1,1.4,0.9,4.2,1.7,27.5,MVP-2ASNBA1
15,2018-19,34,LAL,NBA,SF,55,55,35.2,10.1,19.9,...,1,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,MVP-11ASNBA3
16,2019-20,35,LAL,NBA,PG,67,67,34.6,9.6,19.4,...,1,6.9,7.8,10.2,1.2,0.5,3.9,1.8,25.3,MVP-2ASNBA1
17,2020-21,36,LAL,NBA,PG,45,45,33.4,9.4,18.3,...,0.6,7,7.7,7.8,1.1,0.6,3.7,1.6,25,MVP-13ASNBA2
18,2021-22,37,LAL,NBA,C,56,56,37.2,11.4,21.8,...,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,MVP-10ASNBA3
19,2022-23,38,LAL,NBA,PF,55,54,35.5,11.1,22.2,...,1.2,7.1,8.3,6.8,0.9,0.6,3.2,1.6,28.9,ASNBA3
20,2023-24,39,LAL,NBA,PF,71,71,35.3,9.6,17.9,...,0.9,6.4,7.3,8.3,1.3,0.5,3.5,1.1,25.7,CPOY-10ASNBA3
21,2024-25,40,LAL,NBA,SF,70,70,34.9,9.3,18.1,...,1,6.8,7.8,8.2,1,0.6,3.7,1.4,24.4,MVP-6CPOY-7ASNBA2
22,2025-26,41,LAL,NBA,SF,60,60,33.2,7.9,15.3,...,0.7,5.4,6.1,7.2,1.2,0.6,3,1.4,20.9,AS
23,NaN,NaN,NaN,NaN,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
24,23 Yrs,23 Yrs,23 Yrs,23 Yrs,NaN,1622,1620,37.6,9.8,19.4,...,1.1,6.3,7.5,7.4,1.5,0.7,3.5,1.8,26.8,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),NaN,849,848,39,9.9,20,...,1.2,6.1,7.3,7.3,1.6,0.8,3.5,1.9,27.2,NaN
27,LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),NaN,479,478,34.9,9.8,19,...,1,6.7,7.7,7.9,1.2,0.6,3.5,1.6,25.9,NaN
28,MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),NaN,294,294,38,9.9,18.2,...,1.2,6.4,7.6,6.7,1.7,0.7,3.4,1.7,26.9,NaN

In [4]:
# Check the first few rows of the dataset to understand its structure
dfcopy.shape

(29, 31)

In [5]:
#first ten rows
dfcopy.head(10)

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2003-04,19,CLE,NBA,SG,79,79,39.5,7.9,18.9,...,1.3,4.2,5.5,5.9,1.6,0.7,3.5,1.9,20.9,MVP-9ROY-1
1,2004-05,20,CLE,NBA,SF,80,80,42.4,9.9,21.1,...,1.4,6,7.4,7.2,2.2,0.7,3.3,1.8,27.2,MVP-6ASNBA2
2,2005-06,21,CLE,NBA,SF,79,79,42.5,11.1,23.1,...,0.9,6.1,7,6.6,1.6,0.8,3.3,2.3,31.4,MVP-2ASNBA1
3,2006-07,22,CLE,NBA,SF,78,78,40.9,9.9,20.8,...,1.1,5.7,6.7,6,1.6,0.7,3.2,2.2,27.3,MVP-5ASNBA2
4,2007-08,23,CLE,NBA,SF,75,74,40.4,10.6,21.9,...,1.8,6.1,7.9,7.2,1.8,1.1,3.4,2.2,30,MVP-4ASNBA1
5,2008-09,24,CLE,NBA,SF,81,81,37.7,9.7,19.9,...,1.3,6.3,7.6,7.2,1.7,1.1,3,1.7,28.4,MVP-1DPOY-2ASNBA1DEF1
6,2009-10,25,CLE,NBA,SF,76,76,39,10.1,20.1,...,0.9,6.4,7.3,8.6,1.6,1,3.4,1.6,29.7,MVP-1DPOY-4ASNBA1DEF1
7,2010-11,26,MIA,NBA,SF,79,79,38.8,9.6,18.8,...,1,6.5,7.5,7,1.6,0.6,3.6,2.1,26.7,MVP-3DPOY-9ASNBA1DEF1
8,2011-12,27,MIA,NBA,SF,62,62,37.5,10,18.9,...,1.5,6.4,7.9,6.2,1.9,0.8,3.4,1.5,27.1,MVP-1DPOY-4ASNBA1DEF1
9,2012-13,28,MIA,NBA,PF,76,76,37.9,10.1,17.8,...,1.3,6.8,8,7.3,1.7,0.9,3,1.4,26.8,MVP-1DPOY-2ASNBA1DEF1

In [6]:
#last ten rows 
dfcopy.tail(10)

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
19,2022-23,38,LAL,NBA,PF,55,54,35.5,11.1,22.2,...,1.2,7.1,8.3,6.8,0.9,0.6,3.2,1.6,28.9,ASNBA3
20,2023-24,39,LAL,NBA,PF,71,71,35.3,9.6,17.9,...,0.9,6.4,7.3,8.3,1.3,0.5,3.5,1.1,25.7,CPOY-10ASNBA3
21,2024-25,40,LAL,NBA,SF,70,70,34.9,9.3,18.1,...,1,6.8,7.8,8.2,1,0.6,3.7,1.4,24.4,MVP-6CPOY-7ASNBA2
22,2025-26,41,LAL,NBA,SF,60,60,33.2,7.9,15.3,...,0.7,5.4,6.1,7.2,1.2,0.6,3,1.4,20.9,AS
23,NaN,NaN,NaN,NaN,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
24,23 Yrs,23 Yrs,23 Yrs,23 Yrs,NaN,1622,1620,37.6,9.8,19.4,...,1.1,6.3,7.5,7.4,1.5,0.7,3.5,1.8,26.8,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),CLE (11 Yrs),NaN,849,848,39,9.9,20,...,1.2,6.1,7.3,7.3,1.6,0.8,3.5,1.9,27.2,NaN
27,LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),LAL (8 Yrs),NaN,479,478,34.9,9.8,19,...,1,6.7,7.7,7.9,1.2,0.6,3.5,1.6,25.9,NaN
28,MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),MIA (4 Yrs),NaN,294,294,38,9.9,18.2,...,1.2,6.4,7.6,6.7,1.7,0.7,3.4,1.7,26.9,NaN

In [7]:
#check the data types of each column
dfcopy.dtypes
#integer is sql equivalent to integer
#str is sql equivalent to varchar
#float is sql equivalent to decimal

Season    str
Age       str
Team      str
Lg        str
Pos       str
G         str
GS        str
MP        str
FG        str
FGA       str
FG%       str
3P        str
3PA       str
3P%       str
2P        str
2PA       str
2P%       str
eFG%      str
FT        str
FTA       str
FT%       str
ORB       str
DRB       str
TRB       str
AST       str
STL       str
BLK       str
TOV       str
PF        str
PTS       str
Awards    str
dtype: object

In [8]:
# Check for any missing values in the dataset
dfcopy.isnull().sum()

Season    2
Age       2
Team      2
Lg        2
Pos       5
G         1
GS        1
MP        1
FG        1
FGA       1
FG%       1
3P        1
3PA       1
3P%       1
2P        1
2PA       1
2P%       1
eFG%      1
FT        1
FTA       1
FT%       1
ORB       1
DRB       1
TRB       1
AST       1
STL       1
BLK       1
TOV       1
PF        1
PTS       1
Awards    5
dtype: int64

In [9]:
#list each columns name, data type and non null count
dfcopy.info()

<class 'pandas.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Season  27 non-null     str
 1   Age     27 non-null     str
 2   Team    27 non-null     str
 3   Lg      27 non-null     str
 4   Pos     24 non-null     str
 5   G       28 non-null     str
 6   GS      28 non-null     str
 7   MP      28 non-null     str
 8   FG      28 non-null     str
 9   FGA     28 non-null     str
 10  FG%     28 non-null     str
 11  3P      28 non-null     str
 12  3PA     28 non-null     str
 13  3P%     28 non-null     str
 14  2P      28 non-null     str
 15  2PA     28 non-null     str
 16  2P%     28 non-null     str
 17  eFG%    28 non-null     str
 18  FT      28 non-null     str
 19  FTA     28 non-null     str
 20  FT%     28 non-null     str
 21  ORB     28 non-null     str
 22  DRB     28 non-null     str
 23  TRB     28 non-null     str
 24  AST     28 non-null     str
 25  STL     28 non-null     str
 26  BLK     28 non-null     str
 27  TOV     28 non-null     str
 28  PF      28 non-null     str
 29  PTS     28 non-null     str
 30  Awards  24 non-null     str
dtypes: str(31)
memory usage: 7.2 KB

### What does the data exploration telling me?

1. 29 entries, but LeBron has played 23 seasons.
So there are 6 extra rows. From my .tail(8) output, I was able to see that rows 23-28 shows what the non-seasons are.

2. Every column is str, including the stats.
PTS, Age and G should be numbers/integers. 
3. The non-null counts are valuable info.
- Season has 27 values: 23 seasons + 1 career row + 3 team rows.
- G(games) has 28: those 27 + the repeated header row.
- Pos(position) has 24: 23 seasons + the word "Pos" from the repeated header.

### My next steps:
- Get rid of the excess rows so that i am only keeping the 23 seasons that Lebron has played
- Fixing data types

In [10]:
#.str.isdigit() is True when the text is only digits, like 19, and False for 23 Yrs.
#.fillna(False) treats blank cells as False.
#how it works, it keeps going until there is no age, so obviously the age stops at lebron's latest season.
#23 columns
dfcopy = dfcopy[dfcopy['Age'].str.isdigit().fillna(False)]
dfcopy

,Season,Age,Team,Lg,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,2003-04,19,CLE,NBA,SG,79,79,39.5,7.9,18.9,...,1.3,4.2,5.5,5.9,1.6,0.7,3.5,1.9,20.9,MVP-9ROY-1
1,2004-05,20,CLE,NBA,SF,80,80,42.4,9.9,21.1,...,1.4,6,7.4,7.2,2.2,0.7,3.3,1.8,27.2,MVP-6ASNBA2
2,2005-06,21,CLE,NBA,SF,79,79,42.5,11.1,23.1,...,0.9,6.1,7,6.6,1.6,0.8,3.3,2.3,31.4,MVP-2ASNBA1
3,2006-07,22,CLE,NBA,SF,78,78,40.9,9.9,20.8,...,1.1,5.7,6.7,6,1.6,0.7,3.2,2.2,27.3,MVP-5ASNBA2
4,2007-08,23,CLE,NBA,SF,75,74,40.4,10.6,21.9,...,1.8,6.1,7.9,7.2,1.8,1.1,3.4,2.2,30,MVP-4ASNBA1
5,2008-09,24,CLE,NBA,SF,81,81,37.7,9.7,19.9,...,1.3,6.3,7.6,7.2,1.7,1.1,3,1.7,28.4,MVP-1DPOY-2ASNBA1DEF1
6,2009-10,25,CLE,NBA,SF,76,76,39,10.1,20.1,...,0.9,6.4,7.3,8.6,1.6,1,3.4,1.6,29.7,MVP-1DPOY-4ASNBA1DEF1
7,2010-11,26,MIA,NBA,SF,79,79,38.8,9.6,18.8,...,1,6.5,7.5,7,1.6,0.6,3.6,2.1,26.7,MVP-3DPOY-9ASNBA1DEF1
8,2011-12,27,MIA,NBA,SF,62,62,37.5,10,18.9,...,1.5,6.4,7.9,6.2,1.9,0.8,3.4,1.5,27.1,MVP-1DPOY-4ASNBA1DEF1
9,2012-13,28,MIA,NBA,PF,76,76,37.9,10.1,17.8,...,1.3,6.8,8,7.3,1.7,0.9,3,1.4,26.8,MVP-1DPOY-2ASNBA1DEF1
10,2013-14,29,MIA,NBA,PF,77,77,37.7,10,17.6,...,1.1,5.9,6.9,6.3,1.6,0.3,3.5,1.6,27.1,MVP-2DPOY-6ASNBA1DEF2
11,2014-15,30,CLE,NBA,SF,69,69,36.1,9,18.5,...,0.7,5.3,6,7.4,1.6,0.7,3.9,2,25.3,MVP-3DPOY-13ASNBA1
12,2015-16,31,CLE,NBA,SF,76,76,35.6,9.7,18.6,...,1.5,6,7.4,6.8,1.4,0.6,3.3,1.9,25.3,MVP-3DPOY-11ASNBA1
13,2016-17,32,CLE,NBA,SF,74,74,37.8,9.9,18.2,...,1.3,7.3,8.6,8.7,1.2,0.6,4.1,1.8,26.4,MVP-4DPOY-5ASNBA1
14,2017-18,33,CLE,NBA,PF,82,82,36.9,10.5,19.3,...,1.2,7.5,8.6,9.1,1.4,0.9,4.2,1.7,27.5,MVP-2ASNBA1
15,2018-19,34,LAL,NBA,SF,55,55,35.2,10.1,19.9,...,1,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,MVP-11ASNBA3
16,2019-20,35,LAL,NBA,PG,67,67,34.6,9.6,19.4,...,1,6.9,7.8,10.2,1.2,0.5,3.9,1.8,25.3,MVP-2ASNBA1
17,2020-21,36,LAL,NBA,PG,45,45,33.4,9.4,18.3,...,0.6,7,7.7,7.8,1.1,0.6,3.7,1.6,25,MVP-13ASNBA2
18,2021-22,37,LAL,NBA,C,56,56,37.2,11.4,21.8,...,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,MVP-10ASNBA3
19,2022-23,38,LAL,NBA,PF,55,54,35.5,11.1,22.2,...,1.2,7.1,8.3,6.8,0.9,0.6,3.2,1.6,28.9,ASNBA3
20,2023-24,39,LAL,NBA,PF,71,71,35.3,9.6,17.9,...,0.9,6.4,7.3,8.3,1.3,0.5,3.5,1.1,25.7,CPOY-10ASNBA3
21,2024-25,40,LAL,NBA,SF,70,70,34.9,9.3,18.1,...,1,6.8,7.8,8.2,1,0.6,3.7,1.4,24.4,MVP-6CPOY-7ASNBA2
22,2025-26,41,LAL,NBA,SF,60,60,33.2,7.9,15.3,...,0.7,5.4,6.1,7.2,1.2,0.6,3,1.4,20.9,AS

In [11]:
dfcopy.info()
#now running the .info, you can now see that there are 23 rows which is the amount of seasons Lebron has played
#BUT every column is still a string data type

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Season  23 non-null     str
 1   Age     23 non-null     str
 2   Team    23 non-null     str
 3   Lg      23 non-null     str
 4   Pos     23 non-null     str
 5   G       23 non-null     str
 6   GS      23 non-null     str
 7   MP      23 non-null     str
 8   FG      23 non-null     str
 9   FGA     23 non-null     str
 10  FG%     23 non-null     str
 11  3P      23 non-null     str
 12  3PA     23 non-null     str
 13  3P%     23 non-null     str
 14  2P      23 non-null     str
 15  2PA     23 non-null     str
 16  2P%     23 non-null     str
 17  eFG%    23 non-null     str
 18  FT      23 non-null     str
 19  FTA     23 non-null     str
 20  FT%     23 non-null     str
 21  ORB     23 non-null     str
 22  DRB     23 non-null     str
 23  TRB     23 non-null     str
 24  AST     23 non-null     str
 25  STL     23 non-null     str
 26  BLK     23 non-null     str
 27  TOV     23 non-null     str
 28  PF      23 non-null     str
 29  PTS     23 non-null     str
 30  Awards  23 non-null     str
dtypes: str(31)
memory usage: 5.7 KB

In [12]:
# from the data above, I want the columns SEASON, TEAM, LG, POS, AWARDS to stay as text
text_cols= ['Season', 'Team', 'Lg', 'Pos', 'Awards']
text_cols

['Season', 'Team', 'Lg', 'Pos', 'Awards']

In [13]:
#every other column not those should be a number/integer
num_cols = [col for col in dfcopy.columns if col not in text_cols]
num_cols

['Age',
 'G',
 'GS',
 'MP',
 'FG',
 'FGA',
 'FG%',
 '3P',
 '3PA',
 '3P%',
 '2P',
 '2PA',
 '2P%',
 'eFG%',
 'FT',
 'FTA',
 'FT%',
 'ORB',
 'DRB',
 'TRB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PTS']

In [14]:
#convert them all at once
#.apply(pd.to_numeric) converts each col into numeric datatype
dfcopy[num_cols] = dfcopy[num_cols].apply(pd.to_numeric)
dfcopy.info()

<class 'pandas.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Season  23 non-null     str
 1   Age     23 non-null     int64
 2   Team    23 non-null     str
 3   Lg      23 non-null     str
 4   Pos     23 non-null     str
 5   G       23 non-null     int64
 6   GS      23 non-null     int64
 7   MP      23 non-null     float64
 8   FG      23 non-null     float64
 9   FGA     23 non-null     float64
 10  FG%     23 non-null     float64
 11  3P      23 non-null     float64
 12  3PA     23 non-null     float64
 13  3P%     23 non-null     float64
 14  2P      23 non-null     float64
 15  2PA     23 non-null     float64
 16  2P%     23 non-null     float64
 17  eFG%    23 non-null     float64
 18  FT      23 non-null     float64
 19  FTA     23 non-null     float64
 20  FT%     23 non-null     float64
 21  ORB     23 non-null     float64
 22  DRB     23 non-null     float64
 23  TRB     23 non-null     float64
 24  AST     23 non-null     float64
 25  STL     23 non-null     float64
 26  BLK     23 non-null     float64
 27  TOV     23 non-null     float64
 28  PF      23 non-null     float64
 29  PTS     23 non-null     float64
 30  Awards  23 non-null     str
dtypes: float64(23), int64(3), str(5)
memory usage: 5.7 KB

## Next Steps:
### - Okay, now that I have tackled the data types, as well as keeping the only 23 rows of Lebron's 23 years of basketball - I am ready to now bring this to SQL
- But, before that, the columns FG%, 3p, 2p% have the % which will be problematic in SQL, since % is usually a wildcard in SQL. So, I want every column to be lowercase, with no % and also not starting with a digit.
- Goal is that % becomes _pct, 3p becomes three_p, 2p becomes two_p

In [15]:
#Look at the current names of the csv 
dfcopy.columns

#i can see that there are 9 columns that need to be fixed in terms of % and having number digits
#and also every column needs to be lower case

Index(['Season', 'Age', 'Team', 'Lg', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Awards'],
      dtype='str')

In [16]:
dfcopy.columns = (
    dfcopy.columns
    .str.lower() #FG% to fg%
    .str.replace('%','_pct') #fg% to fg_pct
    .str.replace('3p','three_p') #3p to three_p
    .str.replace('2p','two_p') #2p to two_p
)
dfcopy.columns

Index(['season', 'age', 'team', 'lg', 'pos', 'g', 'gs', 'mp', 'fg', 'fga',
       'fg_pct', 'three_p', 'three_pa', 'three_p_pct', 'two_p', 'two_pa',
       'two_p_pct', 'efg_pct', 'ft', 'fta', 'ft_pct', 'orb', 'drb', 'trb',
       'ast', 'stl', 'blk', 'tov', 'pf', 'pts', 'awards'],
      dtype='str')

In [17]:
#CHECK YOUR WORK

In [18]:
dfcopy['pts'].mean()
#This gives me Lebrons avg points per game across his 23 seasons

np.float64(26.73913043478261)

In [19]:
dfcopy[['season', 'age', 'pts']].sort_values('pts', ascending=False).head()
# Lebrons five highest scoring seasons. This works properly now because the PTS is a number.Text would sort alphabetically.

     season  age   pts
2   2005-06   21  31.4
18  2021-22   37  30.3
4   2007-08   23  30.0
6   2009-10   25  29.7
19  2022-23   38  28.9

## Now that data types are fixed:

- I am curious to know what was his highest assists-per-game season? 
- I am also curious to know how many seasons did he average over 27 points?
- I am curious to know how many seasons and What seasons did he avg more than 8 assists?
- And I am curious to know what seasosn did he play fewer than 60 games?

In [20]:
# What was his highest assists-per-game season? (Hint: reuse the sort pattern above with a different column.)
dfcopy[['season', 'age', 'ast']].sort_values('ast', ascending=False).head()

     season  age   ast
16  2019-20   35  10.2
14  2017-18   33   9.1
13  2016-17   32   8.7
6   2009-10   25   8.6
15  2018-19   34   8.3

In [21]:
#How many seasons did he average over 27 points? (Hint: filter like you did in Step 3, then check .shape or use len().)
(dfcopy['pts'] > 27).sum()

np.int64(12)

In [22]:
#How many seasons did he average 8 or more assists?
#len () is when all you want is a count. the length/how many items or rows are in something
len(dfcopy[dfcopy['ast'] >= 8])

#7 seasons

7

In [23]:
#What seasons from above did he average 8 or more assists?
dfcopy[dfcopy['ast'] >= 8][['season', 'age', 'team', 'ast']]

     season  age team   ast
6   2009-10   25  CLE   8.6
13  2016-17   32  CLE   8.7
14  2017-18   33  CLE   9.1
15  2018-19   34  LAL   8.3
16  2019-20   35  LAL  10.2
20  2023-24   39  LAL   8.3
21  2024-25   40  LAL   8.2

In [24]:
#How many seasons did he play fewer than 60 games?
dfcopy[dfcopy['g'] < 60][['season','age','team','g']]

     season  age team   g
15  2018-19   34  LAL  55
17  2020-21   36  LAL  45
18  2021-22   37  LAL  56
19  2022-23   38  LAL  55